### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Madji** [francescotarantino/BNoteBot#1]
if chose lang bots RU
does not work a reminder. just pressing the button to Recall. the bot displays the text notes. in Eng language it's okay. probably due to the labels on the buttons or something.

**Comment by francescotarantino** [comment]
Thank you for the issue.
I've just fixed it.
[Some translations are missing in russian](https://github.com/franci22/BNoteBot/blob/master/lang/message.en.php#L70), if you want to help I would be happy 😊
